In [1]:
#!jupyter nbconvert --to script KerasAppleCoke.ipynb
#load keras model
#
import picamera
import picamera.array
from keras.models import load_model
import numpy as np
from keras.preprocessing.image import img_to_array
from PIL import Image

Using TensorFlow backend.
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)


In [ ]:
model = load_model('second_try.h5')


In [45]:
with picamera.PiCamera() as camera:
    try:
        while 1:
            with picamera.array.PiRGBArray(camera) as output:
                camera.capture(output, 'rgb')
                x=Image.fromarray(output.array).resize((150,150))
                x = np.expand_dims(x, axis=0)
                pred = model.predict_classes(x)
                probs = model.predict_proba(x)
                print(probs)
                if probs[0][1]==1.0:
                    print("background")
                elif probs[0][0]==1.0:
                    print("apple")
                elif probs[0][2]==1.0:
                    print("coke")
                else:
                    print("background")
    except KeyboardInterrupt:
        print("Exiting...")

/usr/lib/python3/dist-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 720x480 to 736x480
  width, height, fwidth, fheight)))


[[0. 0. 0.]]
background
[[1. 1. 0.]]
background
[[1. 0. 0.]]
apple
[[0. 1. 0.]]
background
[[0. 1. 0.]]
background
[[0. 1. 0.]]
background
[[0. 1. 0.]]
background
[[1. 0. 0.]]
apple
[[1. 0. 0.]]
apple
[[1. 0. 0.]]
apple
[[1. 0. 0.]]
apple
[[1. 0. 0.]]
apple
[[1. 0. 0.]]
apple
[[1. 0. 0.]]
apple
[[1. 0. 0.]]
apple
[[1. 0. 0.]]
apple
[[0. 1. 0.]]
background
[[0. 1. 0.]]
background
[[0. 1. 0.]]
background
[[0. 1. 0.]]
background
[[0.0000000e+00 0.0000000e+00 2.2981046e-30]]
background
[[0. 0. 1.]]
coke
[[0. 0. 0.]]
background
[[0. 0. 0.]]
background
[[0. 0. 0.]]
background
Exiting...
